version: 1
handlers:
    console:
        class: logging.StreamHandler
        formatter: default
        level: DEBUG
        stream: ext://sys.stdout
    file:
        class: logging.FileHandler
        formatter: default
        filename: ../logs/message.log
        mode: a
formatters:
    default:
        format: "%(asctime)s %(levelname)-8s %(name)-15s %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"
loggers: 
    iplogger:
        level: "DEBUG"
        handlers: ["console", "file"]
        